# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LNScrape": "00_LNScrape.ipynb"}

modules = ["LNScrape.py"]

doc_url = "https://teryakizhang.github.io/lnscrape/"

git_url = "https://github.com/teryakizhang/lnscrape/tree/master/"

def custom_doc_links(name): return None
